services:
  mysql:
    image: mysql:8.0
    container_name: db_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ouXkzQBrwcPOBZzAdQYURBYjWkpGvXzs
      MYSQL_DATABASE: development # (vacía) para tus pruebas
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "-uroot",
          "-pouXkzQBrwcPOBZzAdQYURBYjWkpGvXzs",
          "ping",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: db_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: devpass
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "root",
          "--password",
          "devpass",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
  mongo-data:
