CREATE TABLE
  IF NOT EXISTS User (
    idUser INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(55) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(15) NOT NULL DEFAULT 'revisor',
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT UK$EMAIL$USER UNIQUE (email),
    CONSTRAINT CHK$ROL$USER CHECK (rol IN ('admin', 'director', 'revisor'))
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;