CREATE TABLE
  IF NOT EXISTS Category (
    idCategory INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    description VARCHAR(255) NULL
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;