CREATE TABLE IF NOT EXISTS Career (
  idCareer     INT AUTO_INCREMENT PRIMARY KEY,
  name         VARCHAR(55)   NOT NULL,
  schoolName   VARCHAR(120)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;